apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: micro-starter-buildpacks-pipeline
spec:
  params:
    - name: url
      type: string
    - default: master
      name: revision
      type: string
    - description: image URL to push
      name: image
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: subdirectory
          value: micro-starter
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: buildpacks
      params:
        - name: APP_IMAGE
          value: $(params.image)
        - name: SOURCE_SUBPATH
          value: micro-starter
        - name: BUILDER_IMAGE
          value: 'paketobuildpacks/builder:tiny'
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: buildpacks
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: cache
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig
  workspaces:
    - name: shared-workspace
    - name: dockerconfig
    - name: kubeconfig